networks:
  zeebe_network: {}

services:
  postgres:
    container_name: postgres
    image: postgres:17.5-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: identity
      POSTGRES_USER: identity
      POSTGRES_PASSWORD: 't2L@!AqSMg8%I%NmHM'
    networks:
      - zeebe_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.4
    container_name: elasticsearch
    profiles: ['elasticsearch']
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - path.repo=/usr/local/els-snapshots
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - zeebe_network
    restart: always
    volumes:
      - ./els-snapshots:/usr/local/els-snapshots

  opensearch:
    image: opensearchproject/opensearch:2.17.0
    container_name: opensearch
    profiles: ['opensearch']
    environment:
      - cluster.name=opensearch-cluster
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - 'OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m' # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=yourStrongPassword123!
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    ports:
      - 9200:9200
      - 9605:9605 # required for Performance Analyzer
    networks:
      - zeebe_network

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.4
    profiles: ['elasticsearch']
    ports:
      - 5601:5601
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - zeebe_network

  keycloak:
    depends_on:
      - postgres
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0
    command: start-dev --http-relative-path=/auth
    ports:
      - '18080:8080'
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/identity
      KC_DB_USERNAME: identity
      KC_DB_PASSWORD: 't2L@!AqSMg8%I%NmHM'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    healthcheck:
      test: ['CMD-SHELL', 'exec 3<>/dev/tcp/localhost/8080 && echo -e "GET /auth/health/ready HTTP/1.1\nhost: localhost:8080\n" >&3 && timeout 1 cat <&3 | grep "200 OK"']
      interval: 30s
      timeout: 15s
      retries: 8
      start_period: 30s
    networks:
      - zeebe_network

  camunda:
    container_name: camunda
    image: camunda/camunda:SNAPSHOT
    environment:
      - 'JAVA_TOOL_OPTIONS=-Xms512m -Xmx1g'
      - ZEEBE_BROKER_NETWORK_HOST=camunda
      - SPRING_PROFILES_ACTIVE=e2e-test,consolidated-auth,tasklist,broker,operate,identity
      - CAMUNDA_SECURITY_AUTHENTICATION_UNPROTECTEDAPI=false
      - CAMUNDA_SECURITY_AUTHORIZATIONS_ENABLED=true
      - CAMUNDA_SECURITY_AUTHENTICATION_METHOD=BASIC
      - CAMUNDA_SECURITY_MULTITENANCY_CHECKSENABLED=false
      - CAMUNDA_SECURITY_INITIALIZATION_USERS_0_USERNAME=demo
      - CAMUNDA_SECURITY_INITIALIZATION_USERS_0_PASSWORD=demo
      - CAMUNDA_SECURITY_INITIALIZATION_USERS_0_NAME=Demo
      - CAMUNDA_SECURITY_INITIALIZATION_USERS_0_EMAIL=demo@example.com
      - CAMUNDA_SECURITY_INITIALIZATION_DEFAULTROLES_ADMIN_USERS_0=demo
      - CAMUNDA_SECURITY_INITIALIZATION_USERS_1_USERNAME=lisa
      - CAMUNDA_SECURITY_INITIALIZATION_USERS_1_PASSWORD=lisa
      - CAMUNDA_SECURITY_INITIALIZATION_USERS_1_NAME=lisa
      - CAMUNDA_SECURITY_INITIALIZATION_USERS_1_EMAIL=lisa@example.com
      - CAMUNDA_SECURITY_INITIALIZATION_DEFAULTROLES_ADMIN_USERS_1=lisa
      - CAMUNDA_DATA_SECONDARY_STORAGE_TYPE=elasticsearch
      - CAMUNDA_DATA_SECONDARY_STORAGE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_DATA_SECONDARYSTORAGE_ELASTICSEARCH_WAITFORIMPORTERS=false
      - CAMUNDA_TASKLIST_V2_MODE_ENABLED=${CAMUNDA_TASKLIST_V2_MODE_ENABLED:-true}
    ports:
      - 26500:26500
      - 9600:9600
      - 8080:8080
    depends_on:
      - ${DATABASE}
    networks:
      - zeebe_network
    env_file:
      - envs/.env.database.${DATABASE}
